
CREATE TABLE classrooms (
    classroom_id         NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY
        START WITH 1 CONSTRAINT classrooms_pk PRIMARY KEY,
    nr                   VARCHAR2(7) NOT NULL,
    faculty_id           NUMBER(2) NOT NULL
);

CREATE TABLE courses (
    course_id            NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY
        START WITH 1 CONSTRAINT courses_pk PRIMARY KEY,
    type                 VARCHAR2(3) NOT NULL,
    name                 VARCHAR2(30),
    code                 VARCHAR2(6) NOT NULL,
    faculty_id           NUMBER(2) NOT NULL
);

CREATE TABLE exchanges_buy (
    exchange_buy_id                 NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY
        START WITH 1 CONSTRAINT exchanges_buy_pk PRIMARY KEY,
    exchange_sell_id                NUMBER(9) NOT NULL,
    group_id                        NUMBER(4) NOT NULL,
    complete                        CHAR(1) DEFAULT '0' NOT NULL
);

CREATE TABLE exchanges_sell (
    exchange_sell_id                NUMBER(9) GENERATED BY DEFAULT ON NULL AS IDENTITY
        START WITH 1 CONSTRAINT exchanges_sell_pk PRIMARY KEY,
    ug_id                           NUMBER(6) NOT NULL,
    insertion_date                  DATE NOT NULL, 
    completing_exchange_id          NUMBER(9) DEFAULT NULL
);

CREATE UNIQUE INDEX exchanges_sell__idx ON
    exchanges_sell (
        exchange_sell_id
    ASC );

CREATE UNIQUE INDEX exchanges_sell__idxv1 ON
    exchanges_sell (
        ug_id
    ASC );

CREATE TABLE faculties (
    faculty_id NUMBER(2) GENERATED BY DEFAULT ON NULL AS IDENTITY
        START WITH 1 CONSTRAINT faculties_pk PRIMARY KEY,
    name       VARCHAR2(60) NOT NULL,
    shortname  VARCHAR2(4),
    address    VARCHAR2(60)
);

CREATE TABLE groups (
    group_id                NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY
        START WITH 1 CONSTRAINT groups_pk PRIMARY KEY,
    group_nr                NUMBER(3) NOT NULL,
    time_start              NUMBER(4) NOT NULL CONSTRAINT time_start_check CHECK (time_start BETWEEN 0 AND 1439),
    time_end                NUMBER(4) NOT NULL CONSTRAINT time_end_check CHECK (time_end BETWEEN 0 AND 1439),
    day                     NUMBER(1) NOT NULL CONSTRAINT day_check CHECK (day BETWEEN 1 AND 7),
    classroom_id            NUMBER(5) NOT NULL,
    lecturer_id             NUMBER(5) NOT NULL,
    course_id               NUMBER(4) NOT NULL
);

CREATE TABLE lecturers (
    lecturer_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY
        START WITH 1 CONSTRAINT lecturers_pk PRIMARY KEY,
    name        VARCHAR2(40) NOT NULL,
    surname     VARCHAR2(40) NOT NULL,
    rating      NUMBER(1, 2) CONSTRAINT rating_check CHECK (rating BETWEEN 0 AND 10),
    title       VARCHAR2(8) CONSTRAINT title_check CHECK (title IN ('inz', 'mgr', 'mgr inz', 'dr', 'dr hab', 'prof ucz', 'prof'))
);

CREATE TABLE sessions (
    session_id      NUMBER(8) GENERATED BY DEFAULT ON NULL AS IDENTITY
        START WITH 1 CONSTRAINT sessions_pk PRIMARY KEY,
    token           VARCHAR2(40) NOT NULL,
    expiration_time DATE NOT NULL,
    login           VARCHAR2(32) NOT NULL
);

CREATE UNIQUE INDEX sessions__idx ON
    sessions (
        login
    ASC );

CREATE TABLE user_groups (
    ug_id           NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY
        START WITH 1 CONSTRAINT usr_gr_pk PRIMARY KEY,
    login           VARCHAR2(32) NOT NULL,
    group_id        NUMBER(4)
);

CREATE TABLE users (
    login       VARCHAR2(32) NOT NULL CONSTRAINT login_check CHECK (LENGTH(login)>=5),
    passwd_hash VARCHAR2(170) NOT NULL,
    name        VARCHAR2(40),
    surname     VARCHAR2(40),
    email       VARCHAR2(100)
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( login );

ALTER TABLE classrooms
    ADD CONSTRAINT classrooms_faculties_fk FOREIGN KEY ( faculty_id )
        REFERENCES faculties ( faculty_id );

ALTER TABLE courses
    ADD CONSTRAINT courses_faculties_fk FOREIGN KEY ( faculty_id )
        REFERENCES faculties ( faculty_id );

ALTER TABLE exchanges_buy
    ADD CONSTRAINT buy_sell_fk FOREIGN KEY ( exchange_sell_id )
        REFERENCES exchanges_sell ( exchange_sell_id );

ALTER TABLE exchanges_buy
    ADD CONSTRAINT exchanges_buy_groups_fk FOREIGN KEY ( group_id )
        REFERENCES groups ( group_id );

ALTER TABLE exchanges_sell
    ADD CONSTRAINT completing_exc_fk FOREIGN KEY ( completing_exchange_id )
        REFERENCES exchanges_sell ( exchange_sell_id );

ALTER TABLE exchanges_sell
    ADD CONSTRAINT exchanges_sell_user_groups_fk FOREIGN KEY ( ug_id )
        REFERENCES user_groups ( ug_id );

ALTER TABLE groups
    ADD CONSTRAINT groups_classrooms_fk FOREIGN KEY ( classroom_id )
        REFERENCES classrooms ( classroom_id );

ALTER TABLE groups
    ADD CONSTRAINT groups_courses_fk FOREIGN KEY ( course_id )
        REFERENCES courses ( course_id );

ALTER TABLE groups
    ADD CONSTRAINT groups_lecturers_fk FOREIGN KEY ( lecturer_id )
        REFERENCES lecturers ( lecturer_id );

ALTER TABLE sessions
    ADD CONSTRAINT sessions_users_fk FOREIGN KEY ( login )
        REFERENCES users ( login );

ALTER TABLE user_groups
    ADD CONSTRAINT user_groups_groups_fk FOREIGN KEY ( group_id )
        REFERENCES groups ( group_id );

ALTER TABLE user_groups
    ADD CONSTRAINT user_groups_users_fk FOREIGN KEY ( login )
        REFERENCES users ( login );
commit;